smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -13,13 +13,33 @@ commands:
           channel: udapeople
           template: basic_fail_1
 
+
+
+  destroy-environment:
+    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
+    parameters:
+      # Add parameter here
+      workflow_id:
+        type: string
+        default: ${CIRCLE_WORKFLOW_ID:0:7}
+    steps:
+      - run:
+          name: Destroy environments
+          when: on_fail
+          command: |
+            # Your code here
+            aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.workflow_id >>
+            aws s3 rm s3://udapeople-<< parameters.workflow_id >> --recursive
+            aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.workflow_id >>
+          
+ 
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
       # Add parameter here
       workflow_id:
         type: string
-        default: "${CIRCLECI_WORKFLOW_ID}"
+        default: ${CIRCLE_WORKFLOW_ID:0:7}
     steps:
       - run:
           name: Revert migrations
@@ -34,37 +54,7 @@ commands:
               npm install
               npm run migrations:revert
             fi
-  destroy-environment:
-    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
-    parameters:
-      # Add parameter here
-      workflow_id:
-        type: string
-        default: "${CIRCLE_WORKFLOW_ID:0:7}"
-    steps:
-      - run:
-          name: Destroy environments
-          when: on_fail
-          command: |
-            # Your code here
-            echo "Destroying environment: << parameters.workflow_id >> "
-            aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.workflow_id >>
-            aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.workflow_id >>
-            aws s3 rm s3://udapeople-<< parameters.workflow_id >> --recursive
   
-  # remove-bucket-contents:
-  #   description: Remove contents of bucket
-  #   parameters:
-  #     bucket_name:
-  #       type: string
-  #       default: "${CIRCLE_WORKFLOW_ID:0:7}"
-  #   steps:
-  #     - run:
-  #         name: Remove contents of bucket
-  #         when: on_fail
-  #         command: |
-  #           # your code here
-            
 
 jobs:
   build-frontend:
@@ -234,8 +224,8 @@ jobs:
           paths:
             - project/.circleci/ansible/inventory.txt
       
-      - destroy-environment:
-         workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - destroy-environment
+     
       
    
 
@@ -402,54 +392,86 @@ jobs:
 
   smoke-test:
     docker:
-      # Lightweight Docker image
       - image: python:3.7-alpine3.16
     steps:
-      # Checkout code from git
       - checkout
-      - run:
-          name: Install dependencies
-          command: |
-            # your code here
-            apk add --update --no-cache curl aws-cli nodejs npm
-      - run:
-          name: Get backend url
-          command: |
-            # your code here
-            export BACKEND_IP=$(aws ec2 describe-instances \
-            --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-            --query "Reservations[*].Instances[*].PublicDnsName" \
-            --output text)
-            echo "${API_URL}"
-            export API_URL="http://${BACKEND_IP}:3030"
       - run:
           name: Backend smoke test.
           command: |
-            # your code here
-            if [[ 'ok' =~ $(curl -s --connect-timeout 5 http://${BACKEND_IP}:3030/api/status | grep -o ok) ]];then return 0 else return 1;fi
-            # if curl "${API_URL}/api/status" | grep "ok"
-            # then
-            #     return 0
-            # else
-            #     return 1
-            # fi
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --output text)
+
+            export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+            if curl -s $API_URL/api/status | grep "ok"
+            then
+              exit 0
+            else
+              exit 1
+            fi
       - run:
           name: Frontend smoke test.
           command: |
-            # your code here
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
-            echo ${URL} 
-            if curl -s ${URL} | grep "Welcome"
+            FRONTEND_WEBSITE="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"
+            if curl -s $FRONTEND_WEBSITE | grep "Welcome"
             then
-                # Change this to 0 after the job fails
-              return 1
+              exit 1
             else
-              return 1
+              exit 1
             fi
-      # Here's where you will add some code to rollback on failure
-      - revert-migrations
       - destroy-environment
-          # workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - revert-migrations
+
+    # docker:
+    #   # Lightweight Docker image
+    #   - image: python:3.7-alpine3.16
+    # steps:
+    #   # Checkout code from git
+    #   - checkout
+    #   - run:
+    #       name: Install dependencies
+    #       command: |
+    #         # your code here
+    #         apk add --update --no-cache curl aws-cli nodejs npm
+    #   - run:
+    #       name: Get backend url
+    #       command: |
+    #         # your code here
+    #         export BACKEND_IP=$(aws ec2 describe-instances \
+    #         --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+    #         --query "Reservations[*].Instances[*].PublicDnsName" \
+    #         --output text)
+    #         echo "${API_URL}"
+    #         export API_URL="http://${BACKEND_IP}:3030"
+    #   - run:
+    #       name: Backend smoke test.
+    #       command: |
+    #         # your code here
+    #         if [[ 'ok' =~ $(curl -s --connect-timeout 5 http://${BACKEND_IP}:3030/api/status | grep -o ok) ]];then return 0 else return 1;fi
+    #         # if curl "${API_URL}/api/status" | grep "ok"
+    #         # then
+    #         #     return 0
+    #         # else
+    #         #     return 1
+    #         # fi
+      # - run:
+      #     name: Frontend smoke test.
+      #     command: |
+      #       # your code here
+      #       URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+      #       echo ${URL} 
+      #       if curl -s ${URL} | grep "Welcome"
+      #       then
+      #           # Change this to 0 after the job fails
+      #         return 1
+      #       else
+      #         return 1
+      #       fi
+      # # Here's where you will add some code to rollback on failure
+      # - revert-migrations
+      # - destroy-environment
+      #     # workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
 
   cloudfront-update:
